using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using LFG.Permissions;
using LFG.Collezioni;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using LFG.Shared;

namespace LFG.Collezioni;

public class CollezioniAppService : CollezioniAppServiceBase, ICollezioniAppService
{
    //<suite-custom-code-autogenerated>
    public CollezioniAppService(ICollezioneRepository collezioneRepository, CollezioneManager collezioneManager, IDistributedCache<CollezioneDownloadTokenCacheItem, string> downloadTokenCache) : base(collezioneRepository, collezioneManager, downloadTokenCache)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}