using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using LFG.Permissions;
using LFG.Sconti;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using LFG.Shared;

namespace LFG.Sconti;

public class ScontiAppService : ScontiAppServiceBase, IScontiAppService
{
    //<suite-custom-code-autogenerated>
    public ScontiAppService(IScontoRepository scontoRepository, ScontoManager scontoManager, IDistributedCache<ScontoDownloadTokenCacheItem, string> downloadTokenCache) : base(scontoRepository, scontoManager, downloadTokenCache)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}