using LFG.Collezioni;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace LFG.Prodotti;

public class ProdottoManager : ProdottoManagerBase
{
    //<suite-custom-code-autogenerated>
    public ProdottoManager(IProdottoRepository prodottoRepository, IRepository<Collezione, Guid> collezioneRepository) : base(prodottoRepository, collezioneRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}