using LFG.Categorie;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace LFG.Prodotti;

public class Prodotto : ProdottoBase
{
    //<suite-custom-code-autogenerated>
    protected Prodotto()
    {
    }

    public Prodotto(Guid id, Guid? categoriaId, string nome, string prezzo, string sezione, string? descrizione = null, string? codiceSku = null) : base(id, categoriaId, nome, prezzo, sezione, descrizione, codiceSku)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}