using LFG.Collezioni;
using LFG.Helpers;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using JetBrains.Annotations;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace LFG.Prodotti;

public class ProdottoManager : ProdottoManagerBase
{
    //<suite-custom-code-autogenerated>
    public ProdottoManager(IProdottoRepository prodottoRepository) : base(prodottoRepository)
    {
    }
    //</suite-custom-code-autogenerated>

    public override Task<Prodotto> CreateAsync(Guid? categoriaId, Guid? collezioneId, string nome, string prezzo, string sezione, string? descrizione = null, string? codiceSku = null)
    {
        return base.CreateAsync(categoriaId, collezioneId, nome, PrezzoHelper.NormalizzaRaw(prezzo), sezione, descrizione, codiceSku);
    }

    public override Task<Prodotto> UpdateAsync(Guid id, Guid? categoriaId, Guid? collezioneId, string nome, string prezzo, string sezione, string? descrizione = null, string? codiceSku = null, [CanBeNull] string? concurrencyStamp = null)
    {
        return base.UpdateAsync(id, categoriaId, collezioneId, nome, PrezzoHelper.NormalizzaRaw(prezzo), sezione, descrizione, codiceSku, concurrencyStamp);
    }
}