using LFG.Clienti;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace LFG.Indirizzi;

public class Indirizzo : IndirizzoBase
{
    //<suite-custom-code-autogenerated>
    protected Indirizzo()
    {
    }

    public Indirizzo(Guid id, Guid? clienteId, string via, string cap, string? paese = null, string? citta = null, string? provincia = null) : base(id, clienteId, via, cap, paese, citta, provincia)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}