using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace LFG.Indirizzi;

public class IndirizzoManager : IndirizzoManagerBase
{
    //<suite-custom-code-autogenerated>
    public IndirizzoManager(IIndirizzoRepository indirizzoRepository) : base(indirizzoRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}