using LFG.Shared;
using LFG.VarianteProdotti;
using LFG.Ordini;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using LFG.Permissions;
using LFG.RigaOrdini;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using LFG.Shared;

namespace LFG.RigaOrdini;

public class RigaOrdiniAppService : RigaOrdiniAppServiceBase, IRigaOrdiniAppService
{
    //<suite-custom-code-autogenerated>
    public RigaOrdiniAppService(IRigaOrdineRepository rigaOrdineRepository, RigaOrdineManager rigaOrdineManager, IDistributedCache<RigaOrdineDownloadTokenCacheItem, string> downloadTokenCache, IRepository<LFG.Ordini.Ordine, Guid> ordineRepository, IRepository<LFG.VarianteProdotti.VarianteProdotto, Guid> varianteProdottoRepository) : base(rigaOrdineRepository, rigaOrdineManager, downloadTokenCache, ordineRepository, varianteProdottoRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}