using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace LFG.Clienti;

public class ClienteManager : ClienteManagerBase
{
    //<suite-custom-code-autogenerated>
    public ClienteManager(IClienteRepository clienteRepository) : base(clienteRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}