using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace LFG.Clienti;

public class Cliente : ClienteBase
{
    //<suite-custom-code-autogenerated>
    protected Cliente()
    {
    }

    public Cliente(Guid id, string nome, string cognome, string genere, string email, string telefono, string sezione, string nazionalita, DateTime? dataNascita = null) : base(id, nome, cognome, genere, email, telefono, sezione, nazionalita, dataNascita)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}