using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace LFG.Ordini;

public class OrdineManager : OrdineManagerBase
{
    //<suite-custom-code-autogenerated>
    public OrdineManager(IOrdineRepository ordineRepository) : base(ordineRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}