using LFG.Sconti;
using LFG.Clienti;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace LFG.Ordini;

public class Ordine : OrdineBase
{
    //<suite-custom-code-autogenerated>
    protected Ordine()
    {
    }

    public Ordine(Guid id, Guid? clienteId, Guid? scontoId, DateTime dataOrdine, decimal importoTotale, string? stato = null, string? indSpedizione = null, string? metodoPagamento = null) : base(id, clienteId, scontoId, dataOrdine, importoTotale, stato, indSpedizione, metodoPagamento)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}