using LFG.Shared;
using LFG.Shared;
using LFG.Shared;
using LFG.VarianteProdotti;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using LFG.Permissions;
using LFG.ImmagineVarianti;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using LFG.Shared;

namespace LFG.ImmagineVarianti;

public class ImmagineVariantiAppService : ImmagineVariantiAppServiceBase, IImmagineVariantiAppService
{
    //<suite-custom-code-autogenerated>
    public ImmagineVariantiAppService(IImmagineVarianteRepository immagineVarianteRepository, ImmagineVarianteManager immagineVarianteManager, IDistributedCache<ImmagineVarianteDownloadTokenCacheItem, string> downloadTokenCache, IRepository<LFG.VarianteProdotti.VarianteProdotto, Guid> varianteProdottoRepository) : base(immagineVarianteRepository, immagineVarianteManager, downloadTokenCache, varianteProdottoRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}