using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using LFG.Permissions;
using LFG.VarianteProdotti;

namespace LFG.VarianteProdotti;

public class VarianteProdottiAppService : VarianteProdottiAppServiceBase, IVarianteProdottiAppService
{
    //<suite-custom-code-autogenerated>
    public VarianteProdottiAppService(IVarianteProdottoRepository varianteProdottoRepository, VarianteProdottoManager varianteProdottoManager) : base(varianteProdottoRepository, varianteProdottoManager)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}