using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace LFG.VarianteProdotti;

public class VarianteProdottoManager : VarianteProdottoManagerBase
{
    //<suite-custom-code-autogenerated>
    public VarianteProdottoManager(IVarianteProdottoRepository varianteProdottoRepository) : base(varianteProdottoRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}