using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace LFG.VarianteProdotti;

public class VarianteProdotto : VarianteProdottoBase
{
    //<suite-custom-code-autogenerated>
    protected VarianteProdotto()
    {
    }

    public VarianteProdotto(Guid id, Guid prodottoId, int qtaMagazzino, string? taglia = null, string? colore = null, string? materiale = null, string? urlImmagine = null) : base(id, prodottoId, qtaMagazzino, taglia, colore, materiale, urlImmagine)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}