using LFG.Shared;
using LFG.Clienti;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using LFG.Permissions;
using LFG.Indirizzi;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using LFG.Shared;

namespace LFG.Indirizzi;

public class IndirizziAppService : IndirizziAppServiceBase, IIndirizziAppService
{
    //<suite-custom-code-autogenerated>
    public IndirizziAppService(IIndirizzoRepository indirizzoRepository, IndirizzoManager indirizzoManager, IDistributedCache<IndirizzoDownloadTokenCacheItem, string> downloadTokenCache, IRepository<LFG.Clienti.Cliente, Guid> clienteRepository) : base(indirizzoRepository, indirizzoManager, downloadTokenCache, clienteRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}