using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace LFG.ElementoListe;

public class ElementoListaManager : ElementoListaManagerBase
{
    //<suite-custom-code-autogenerated>
    public ElementoListaManager(IElementoListaRepository elementoListaRepository) : base(elementoListaRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}