using LFG.VarianteProdotti;
using LFG.ListeDesideri;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace LFG.ElementoListe;

public class ElementoLista : ElementoListaBase
{
    //<suite-custom-code-autogenerated>
    protected ElementoLista()
    {
    }

    public ElementoLista(Guid id, Guid varianteProdottoId, Guid? listaDesideriId, DateTime dataAggiunta) : base(id, varianteProdottoId, listaDesideriId, dataAggiunta)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}