using LFG.Shared;
using LFG.Shared;
using LFG.Clienti;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using LFG.Permissions;
using LFG.ListeDesideri;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using LFG.Shared;

namespace LFG.ListeDesideri;

public class ListeDesideriAppService : ListeDesideriAppServiceBase, IListeDesideriAppService
{
    //<suite-custom-code-autogenerated>
    public ListeDesideriAppService(IListaDesideriRepository listaDesideriRepository, ListaDesideriManager listaDesideriManager, IDistributedCache<ListaDesideriDownloadTokenCacheItem, string> downloadTokenCache, IRepository<LFG.Clienti.Cliente, Guid> clienteRepository) : base(listaDesideriRepository, listaDesideriManager, downloadTokenCache, clienteRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}