using LFG.Shared;
using LFG.Sconti;
using LFG.Shared;
using LFG.Clienti;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using LFG.Permissions;
using LFG.Ordini;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using LFG.Shared;

namespace LFG.Ordini;

public class OrdiniAppService : OrdiniAppServiceBase, IOrdiniAppService
{
    //<suite-custom-code-autogenerated>
    public OrdiniAppService(IOrdineRepository ordineRepository, OrdineManager ordineManager, IDistributedCache<OrdineDownloadTokenCacheItem, string> downloadTokenCache, IRepository<LFG.Clienti.Cliente, Guid> clienteRepository, IRepository<LFG.Sconti.Sconto, Guid> scontoRepository) : base(ordineRepository, ordineManager, downloadTokenCache, clienteRepository, scontoRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}