using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace LFG.Recensioni;

public class RecensioneManager : RecensioneManagerBase
{
    //<suite-custom-code-autogenerated>
    public RecensioneManager(IRecensioneRepository recensioneRepository) : base(recensioneRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}