using LFG.Clienti;
using LFG.Prodotti;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace LFG.Recensioni;

public class Recensione : RecensioneBase
{
    //<suite-custom-code-autogenerated>
    protected Recensione()
    {
    }

    public Recensione(Guid id, Guid? clienteId, Guid? prodottoId, int valutazione, DateTime dataRecensione, string? commento = null) : base(id, clienteId, prodottoId, valutazione, dataRecensione, commento)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}