using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace LFG.Collezioni;

public class CollezioneManager : CollezioneManagerBase
{
    //<suite-custom-code-autogenerated>
    public CollezioneManager(ICollezioneRepository collezioneRepository) : base(collezioneRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}