using LFG.Ordini;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace LFG.Pagamenti;

public class Pagamento : PagamentoBase
{
    //<suite-custom-code-autogenerated>
    protected Pagamento()
    {
    }

    public Pagamento(Guid id, Guid? ordineId, decimal importo, DateTime dataPagamento, string idTransazione, string? metodo = null, string? stato = null) : base(id, ordineId, importo, dataPagamento, idTransazione, metodo, stato)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}