using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace LFG.Pagamenti;

public class PagamentoManager : PagamentoManagerBase
{
    //<suite-custom-code-autogenerated>
    public PagamentoManager(IPagamentoRepository pagamentoRepository) : base(pagamentoRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}