using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace LFG.RigaOrdini;

public class RigaOrdineManager : RigaOrdineManagerBase
{
    //<suite-custom-code-autogenerated>
    public RigaOrdineManager(IRigaOrdineRepository rigaOrdineRepository) : base(rigaOrdineRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}