using LFG.Ordini;
using LFG.VarianteProdotti;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace LFG.RigaOrdini;

public class RigaOrdine : RigaOrdineBase
{
    //<suite-custom-code-autogenerated>
    protected RigaOrdine()
    {
    }

    public RigaOrdine(Guid id, Guid? ordineId, Guid? varianteProdottoId, int quantita, decimal prezzoUnitario) : base(id, ordineId, varianteProdottoId, quantita, prezzoUnitario)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}