using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace LFG.Sconti;

public class ScontoManager : ScontoManagerBase
{
    //<suite-custom-code-autogenerated>
    public ScontoManager(IScontoRepository scontoRepository) : base(scontoRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}