using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace LFG.Sconti;

public class Sconto : ScontoBase
{
    //<suite-custom-code-autogenerated>
    protected Sconto()
    {
    }

    public Sconto(Guid id, string codice, decimal valore, DateTime validoDal, DateTime validoAl, string sezione, string? tipo = null, int? limiteUtilizzi = null) : base(id, codice, valore, validoDal, validoAl, sezione, tipo, limiteUtilizzi)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}