using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace LFG.ListeDesideri;

public class ListaDesideriManager : ListaDesideriManagerBase
{
    //<suite-custom-code-autogenerated>
    public ListaDesideriManager(IListaDesideriRepository listaDesideriRepository) : base(listaDesideriRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}