using LFG.Clienti;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace LFG.ListeDesideri;

public class ListaDesideri : ListaDesideriBase
{
    //<suite-custom-code-autogenerated>
    protected ListaDesideri()
    {
    }

    public ListaDesideri(Guid id, Guid? clienteId, DateTime dataCreazione, string nomeLista) : base(id, clienteId, dataCreazione, nomeLista)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}