using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace LFG.ImmagineVarianti;

public class ImmagineVarianteManager : ImmagineVarianteManagerBase
{
    //<suite-custom-code-autogenerated>
    public ImmagineVarianteManager(IImmagineVarianteRepository immagineVarianteRepository) : base(immagineVarianteRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}