using LFG.VarianteProdotti;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace LFG.ImmagineVarianti;

public class ImmagineVariante : ImmagineVarianteBase
{
    //<suite-custom-code-autogenerated>
    protected ImmagineVariante()
    {
    }

    public ImmagineVariante(Guid id, Guid varianteProdottoId, string url, int ordine) : base(id, varianteProdottoId, url, ordine)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}