using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using LFG.Permissions;
using LFG.Clienti;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using LFG.Shared;

namespace LFG.Clienti;

public class ClientiAppService : ClientiAppServiceBase, IClientiAppService
{
    //<suite-custom-code-autogenerated>
    public ClientiAppService(IClienteRepository clienteRepository, ClienteManager clienteManager, IDistributedCache<ClienteDownloadTokenCacheItem, string> downloadTokenCache) : base(clienteRepository, clienteManager, downloadTokenCache)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}