using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace LFG.Categorie;

public class CategoriaManager : CategoriaManagerBase
{
    //<suite-custom-code-autogenerated>
    public CategoriaManager(ICategoriaRepository categoriaRepository) : base(categoriaRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}