using LFG.Shared;
using LFG.Ordini;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using LFG.Permissions;
using LFG.Pagamenti;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using LFG.Shared;

namespace LFG.Pagamenti;

public class PagamentiAppService : PagamentiAppServiceBase, IPagamentiAppService
{
    //<suite-custom-code-autogenerated>
    public PagamentiAppService(IPagamentoRepository pagamentoRepository, PagamentoManager pagamentoManager, IDistributedCache<PagamentoDownloadTokenCacheItem, string> downloadTokenCache, IRepository<LFG.Ordini.Ordine, Guid> ordineRepository) : base(pagamentoRepository, pagamentoManager, downloadTokenCache, ordineRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}