using LFG.Shared;
using LFG.Prodotti;
using LFG.Clienti;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using LFG.Permissions;
using LFG.Recensioni;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using LFG.Shared;

namespace LFG.Recensioni;

public class RecensioniAppService : RecensioniAppServiceBase, IRecensioniAppService
{
    //<suite-custom-code-autogenerated>
    public RecensioniAppService(IRecensioneRepository recensioneRepository, RecensioneManager recensioneManager, IDistributedCache<RecensioneDownloadTokenCacheItem, string> downloadTokenCache, IRepository<LFG.Clienti.Cliente, Guid> clienteRepository, IRepository<LFG.Prodotti.Prodotto, Guid> prodottoRepository) : base(recensioneRepository, recensioneManager, downloadTokenCache, clienteRepository, prodottoRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}