using LFG.Shared;
using LFG.Collezioni;
using LFG.Shared;
using LFG.Shared;
using LFG.Categorie;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using LFG.Permissions;
using LFG.Prodotti;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using LFG.Shared;

namespace LFG.Prodotti;

public class ProdottiAppService : ProdottiAppServiceBase, IProdottiAppService
{
    //<suite-custom-code-autogenerated>
    public ProdottiAppService(IProdottoRepository prodottoRepository, ProdottoManager prodottoManager, IDistributedCache<ProdottoDownloadTokenCacheItem, string> downloadTokenCache, IRepository<LFG.Categorie.Categoria, Guid> categoriaRepository, IRepository<LFG.Collezioni.Collezione, Guid> collezioneRepository) : base(prodottoRepository, prodottoManager, downloadTokenCache, categoriaRepository, collezioneRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}