using LFG.Shared;
using LFG.Collezioni;
using LFG.Shared;
using LFG.Shared;
using LFG.Categorie;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using LFG.Permissions;
using LFG.Prodotti;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using LFG.Shared;

namespace LFG.Prodotti;

public class ProdottiAppService : ProdottiAppServiceBase, IProdottiAppService
{
    //<suite-custom-code-autogenerated>
    public ProdottiAppService(IProdottoRepository prodottoRepository, ProdottoManager prodottoManager, IDistributedCache<ProdottoDownloadTokenCacheItem, string> downloadTokenCache, IRepository<LFG.Categorie.Categoria, Guid> categoriaRepository, IRepository<LFG.Collezioni.Collezione, Guid> collezioneRepository) : base(prodottoRepository, prodottoManager, downloadTokenCache, categoriaRepository, collezioneRepository)
    {
    }
    //</suite-custom-code-autogenerated>

    [Authorize(LFGPermissions.Prodotti.Edit)]
    public async Task<PrezzoNormalizzazioneResultDto> NormalizzaPrezziAsync()
    {
        var result = new PrezzoNormalizzazioneResultDto();

        var tutti = await _prodottoRepository.GetListAsync();
        result.TotaleEsaminati = tutti.Count;

        foreach (var prod in tutti)
        {
            var prima = prod.Prezzo;
            var dopo  = LFG.Helpers.PrezzoHelper.NormalizzaRaw(prima);

            // Anomalia: stringa non vuota che non produce un valore parsabile
            var anomalia   = dopo == prima && LFG.Helpers.PrezzoHelper.Parse(prima) == 0m
                             && !string.IsNullOrWhiteSpace(prima);
            var modificato = dopo != prima;

            result.Log.Add(new PrezzoConversioneLog
            {
                ProdottoId = prod.Id,
                Nome       = prod.Nome,
                PrimaDi    = prima,
                DopoDi     = dopo,
                Modificato = modificato,
                Anomalia   = anomalia,
            });

            if (anomalia)
            {
                result.TotaleAnomalie++;
                Logger.LogWarning(
                    "[NormalizzaPrezzi] ANOMALIA prodotto {Id} '{Nome}': '{Prima}' non convertibile",
                    prod.Id, prod.Nome, prima);
            }
            else if (modificato)
            {
                result.TotaleModificati++;
                Logger.LogInformation(
                    "[NormalizzaPrezzi] prodotto {Id} '{Nome}': '{Prima}' -> '{Dopo}'",
                    prod.Id, prod.Nome, prima, dopo);

                prod.Prezzo = dopo;
                await _prodottoRepository.UpdateAsync(prod, autoSave: true);
            }
        }

        Logger.LogInformation(
            "[NormalizzaPrezzi] Completato. Esaminati={E}, Modificati={M}, Anomalie={A}",
            result.TotaleEsaminati, result.TotaleModificati, result.TotaleAnomalie);

        return result;
    }
}