using LFG.Shared;
using LFG.ListeDesideri;
using LFG.VarianteProdotti;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using LFG.Permissions;
using LFG.ElementoListe;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using LFG.Shared;

namespace LFG.ElementoListe;

public class ElementoListeAppService : ElementoListeAppServiceBase, IElementoListeAppService
{
    //<suite-custom-code-autogenerated>
    public ElementoListeAppService(IElementoListaRepository elementoListaRepository, ElementoListaManager elementoListaManager, IDistributedCache<ElementoListaDownloadTokenCacheItem, string> downloadTokenCache, IRepository<LFG.VarianteProdotti.VarianteProdotto, Guid> varianteProdottoRepository, IRepository<LFG.ListeDesideri.ListaDesideri, Guid> listaDesideriRepository) : base(elementoListaRepository, elementoListaManager, downloadTokenCache, varianteProdottoRepository, listaDesideriRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}